# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4999298495106a6abe9de1cfb704693a"
application_url = "https://dolls-blvd-females-independently.trycloudflare.com"
embedded = true
name = "Product Reviews"
handle = "product-reviews-156"

[build]
include_config_on_deploy = true
dev_store_url = "mai-my-store.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dolls-blvd-females-independently.trycloudflare.com/auth/callback",
  "https://dolls-blvd-females-independently.trycloudflare.com/auth/shopify/callback",
  "https://dolls-blvd-females-independently.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
